# Generated by Django 6.0 on 2025-12-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=20)),
                ('schoolname', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=100)),
                ('math', models.IntegerField()),
                ('sci', models.IntegerField()),
                ('sst', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('eng', models.IntegerField()),
            ],
        ),
    ]
